// <auto-generated />
using Api_cookies.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_cookies.Migrations
{
    [DbContext(typeof(CookieSalmonDbContext))]
    [Migration("20231003172129_suii")]
    partial class suii
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api_cookies.Models.SalesPerHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<int>("cookiestandId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("cookiestandId");

                    b.ToTable("SalesHour");
                });

            modelBuilder.Entity("Api_cookies.Models.cookiestand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Average_Cookies_Per_Sale")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Max_Customer_Per_Hour")
                        .HasColumnType("int");

                    b.Property<int>("Min_Customer_Pre_Hour")
                        .HasColumnType("int");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CookiesStand");
                });

            modelBuilder.Entity("Api_cookies.Models.SalesPerHour", b =>
                {
                    b.HasOne("Api_cookies.Models.cookiestand", "cookieStand")
                        .WithMany("Hour")
                        .HasForeignKey("cookiestandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cookieStand");
                });

            modelBuilder.Entity("Api_cookies.Models.cookiestand", b =>
                {
                    b.Navigation("Hour");
                });
#pragma warning restore 612, 618
        }
    }
}
